### USERS ###

### Récuperation de tout les utilisateurs ###
GET  http://localhost:4000/bfb/users
### Récuperation d'un utilisateur par son id ###
GET  http://localhost:4000/bfb/users/1
### Création d'un utilisateur ###
POST  http://localhost:4000/bfb/users
Content-Type: application/json

{
  "firstname": "jeas",
  "lastname": "tot",
  "email": "jeharles.toupet@example.com",
  "password": "pass552ord",
  "username": "57-è-(èkhjk22t"
}
### Modification d'un utilisateur ###
PATCH  http://localhost:4000/bfb/users/2
Content-Type: application/json

{
"firstname": "Krusty",
  "lastname": "LeCLown",
  "email": "Krustfhg@fhgfhample.com",
  "password": "phgjghjuyy",
  "username": "Krusshow_show"
}
### Suppression d'un utilisateurs ###
DELETE  http://localhost:4000/bfb/users/1