### USERS ###

### Récuperation de tout les utilisateurs ###
GET  http://localhost:4000/bfb/users
### Récuperation d'un utilisateur par son id ###
GET  http://localhost:4000/bfb/users/2
### Création d'un utilisateur ###
POST  http://localhost:4000/bfb/users
Content-Type: application/json

{
  "firstname": "jeas",
  "lastname": "tot",
  "email": "jehaehjgfs.toupet@example.com",
  "password": "pass5ghf52ord",
  "username": "57tthythjk22t"

}
### Modification d'un utilisateur ###
PATCH  http://localhost:4000/bfb/users/2
Content-Type: application/json

{
  "firstname": "Krusty",
  "lastname": "LeCLown",
  "email": "Krustfhgvvj@fhgfhample.com",
  "password": "phg",
  "username": "Krusshow_show"
}
### Suppression d'un utilisateurs ###
DELETE  http://localhost:4000/bfb/users/1

### RECIPE ###

### Récupération de toutes les recettes ###
GET  http://localhost:4000/bfb/recipe
### Récupération d'une recette par son id ###
GET  http://localhost:4000/bfb/recipe/4
### Création d'une recette ###
POST  http://localhost:4000/bfb/recipe
Content-Type: application/json

{
  "title": "Recette 2",
  "slug": "recette-recette",
  "number_of_parts": "4",
  "description": "Description de la recette 1",
  "ingredients": "Ingrédients de la recette 1",
  "instruction": "Instructions de la recette 1",
  "preparation_time": "30",
  "cooking_time": "15",
  "picture": "image1.jpg",
  "user_id": "2"
}
### Modification d'une recette ###
PATCH  http://localhost:4000/bfb/recipe/6
Content-Type: application/json

{
  "title": "Recette modifiée",
  "number_of_parts": "6",
  "description": "Description de la recette 1",
  "ingredients": "Ingrédients de la recette 1",
  "instruction": "Instructions de la recette 1",
  "preparation_time": "120",
  "cooking_time": "15",
  "picture": "image1.jpg"
}
### Suppression d'une recette ###
DELETE  http://localhost:4000/bfb/recipe/7